import "dotenv/config";
import pg from "pg";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "../src/generated/client/index.js";

const connectionString = process.env.DATABASE_URL;
if (!connectionString) throw new Error("DATABASE_URL no definida");

const pool = new pg.Pool({ connectionString });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

const achievementsData = [
  { title: "Debutante", description: "Juega tu primer partido", category: "MATCH", condition_type: "MATCHES_PLAYED", condition_value: 1, reward_type: "STAT_BOOST", reward_value: { pace: 0.5 }, is_pro_exclusive: false, sort_order: 101 },
  { title: "Primer Gol (figurado)", description: "Participa en 3 partidos", category: "MATCH", condition_type: "MATCHES_PLAYED", condition_value: 3, reward_type: "STAT_BOOST", reward_value: { league_overall: 0.25 }, is_pro_exclusive: false, sort_order: 102 },
  { title: "Regular", description: "Juega 10 partidos en una liga", category: "MATCH", condition_type: "MATCHES_PLAYED", condition_value: 10, reward_type: "STAT_BOOST", reward_value: { technique: 0.5 }, is_pro_exclusive: false, sort_order: 103 },
  { title: "Frecuente", description: "Juega 25 partidos", category: "MATCH", condition_type: "MATCHES_PLAYED", condition_value: 25, reward_type: "STAT_BOOST", reward_value: { physical: 0.5 }, is_pro_exclusive: false, sort_order: 104 },
  { title: "Veterano", description: "Juega 50 partidos", category: "MATCH", condition_type: "MATCHES_PLAYED", condition_value: 50, reward_type: "STAT_BOOST", reward_value: { defense: 0.5, attack: 0.5 }, is_pro_exclusive: false, sort_order: 105 },
  { title: "Racha Ganadora I", description: "Gana 3 partidos seguidos", category: "STREAK", condition_type: "WIN_STREAK", condition_value: 3, reward_type: "STAT_BOOST", reward_value: { pace: 1 }, is_pro_exclusive: false, sort_order: 111 },
  { title: "Racha Ganadora II", description: "Gana 5 partidos seguidos", category: "STREAK", condition_type: "WIN_STREAK", condition_value: 5, reward_type: "STAT_BOOST", reward_value: { league_overall: 0.5 }, is_pro_exclusive: false, sort_order: 112 },
  { title: "Racha Ganadora III", description: "Gana 7 partidos seguidos", category: "STREAK", condition_type: "WIN_STREAK", condition_value: 7, reward_type: "STAT_BOOST", reward_value: { defense: 1, attack: 1 }, is_pro_exclusive: false, sort_order: 113 },
  { title: "Racha Ganadora IV", description: "Gana 10 partidos seguidos", category: "STREAK", condition_type: "WIN_STREAK", condition_value: 10, reward_type: "COSMETIC", reward_value: { cosmetic_key: "streak_frame", cosmetic_type: "FRAME" }, is_pro_exclusive: true, sort_order: 114 },
  { title: "Invencible", description: "Gana 15 partidos seguidos", category: "STREAK", condition_type: "WIN_STREAK", condition_value: 15, reward_type: "COSMETIC", reward_value: { cosmetic_key: "gold_frame", cosmetic_type: "FRAME" }, is_pro_exclusive: true, sort_order: 115 },
  { title: "La Muralla", description: "Saca 9 o más en Defensa en un partido", category: "MATCH", condition_type: "DEFENSE_SINGLE", condition_value: 9, reward_type: "STAT_BOOST", reward_value: { defense: 1 }, is_pro_exclusive: false, sort_order: 121 },
  { title: "Muro de Hierro", description: "Saca 10 en Defensa en un partido", category: "MATCH", condition_type: "DEFENSE_SINGLE", condition_value: 10, reward_type: "STAT_BOOST", reward_value: { defense: 1, physical: 0.5 }, is_pro_exclusive: false, sort_order: 122 },
  { title: "El Francotirador", description: "Saca 9 o más en Ataque en un partido", category: "MATCH", condition_type: "ATTACK_SINGLE", condition_value: 9, reward_type: "STAT_BOOST", reward_value: { attack: 1 }, is_pro_exclusive: false, sort_order: 123 },
  { title: "Romperredes", description: "Saca 10 en Ataque en un partido", category: "MATCH", condition_type: "ATTACK_SINGLE", condition_value: 10, reward_type: "STAT_BOOST", reward_value: { attack: 1, pace: 0.5 }, is_pro_exclusive: false, sort_order: 124 },
  { title: "Relámpago", description: "Saca 9 o más en Ritmo en un partido", category: "MATCH", condition_type: "PACE_SINGLE", condition_value: 9, reward_type: "STAT_BOOST", reward_value: { pace: 1 }, is_pro_exclusive: false, sort_order: 125 },
  { title: "Técnica Pura", description: "Saca 9 o más en Técnica en un partido", category: "MATCH", condition_type: "TECHNIQUE_SINGLE", condition_value: 9, reward_type: "STAT_BOOST", reward_value: { technique: 1 }, is_pro_exclusive: false, sort_order: 126 },
  { title: "Fuerza Bruta", description: "Saca 9 o más en Físico en un partido", category: "MATCH", condition_type: "PHYSICAL_SINGLE", condition_value: 9, reward_type: "STAT_BOOST", reward_value: { physical: 1 }, is_pro_exclusive: false, sort_order: 127 },
  { title: "Equilibrado", description: "Saca 8 o más en Promedio General en un partido", category: "MATCH", condition_type: "OVERALL_SINGLE", condition_value: 8, reward_type: "STAT_BOOST", reward_value: { league_overall: 0.5 }, is_pro_exclusive: false, sort_order: 128 },
  { title: "Estrella del Partido", description: "Saca 9 o más en Promedio General en un partido", category: "MATCH", condition_type: "OVERALL_SINGLE", condition_value: 9, reward_type: "STAT_BOOST", reward_value: { league_overall: 0.5, technique: 0.5 }, is_pro_exclusive: false, sort_order: 129 },
  { title: "MVP Novato", description: "Gana tu primer MVP", category: "MATCH", condition_type: "MVP_COUNT", condition_value: 1, reward_type: "STAT_BOOST", reward_value: { league_overall: 0.5 }, is_pro_exclusive: false, sort_order: 131 },
  { title: "MVP Recurrente", description: "Gana 3 MVPs", category: "MATCH", condition_type: "MVP_COUNT", condition_value: 3, reward_type: "STAT_BOOST", reward_value: { technique: 1, attack: 0.5 }, is_pro_exclusive: false, sort_order: 132 },
  { title: "MVP Consagrado", description: "Gana 5 MVPs", category: "MATCH", condition_type: "MVP_COUNT", condition_value: 5, reward_type: "COSMETIC", reward_value: { cosmetic_key: "mvp_frame", cosmetic_type: "FRAME" }, is_pro_exclusive: true, sort_order: 133 },
  { title: "MVP Legendario", description: "Gana 10 MVPs", category: "MATCH", condition_type: "MVP_COUNT", condition_value: 10, reward_type: "COSMETIC", reward_value: { cosmetic_key: "gold_frame", cosmetic_type: "FRAME" }, is_pro_exclusive: true, sort_order: 134 },
  { title: "MVP Épico", description: "Gana 25 MVPs", category: "MATCH", condition_type: "MVP_COUNT", condition_value: 25, reward_type: "COSMETIC", reward_value: { cosmetic_key: "crown_frame", cosmetic_type: "FRAME" }, is_pro_exclusive: true, sort_order: 135 },
  { title: "Portero Firme", description: "Gana la valla invicta 1 vez (equipo no recibe goles)", category: "MATCH", condition_type: "CLEAN_SHEET_COUNT", condition_value: 1, reward_type: "STAT_BOOST", reward_value: { defense: 0.5 }, is_pro_exclusive: false, sort_order: 141 },
  { title: "El Muro", description: "Gana la valla invicta 3 veces", category: "MATCH", condition_type: "CLEAN_SHEET_COUNT", condition_value: 3, reward_type: "STAT_BOOST", reward_value: { defense: 1 }, is_pro_exclusive: false, sort_order: 142 },
  { title: "Muralla Impenetrable", description: "Gana la valla invicta 5 veces", category: "MATCH", condition_type: "CLEAN_SHEET_COUNT", condition_value: 5, reward_type: "COSMETIC", reward_value: { cosmetic_key: "wall_banner", cosmetic_type: "BANNER" }, is_pro_exclusive: true, sort_order: 143 },
  { title: "Socio Ideal", description: "Juega 5 partidos con el mismo compañero ganando", category: "SOCIAL", condition_type: "SAME_PARTNER_WINS", condition_value: 5, reward_type: "STAT_BOOST", reward_value: { technique: 0.5, physical: 0.5 }, is_pro_exclusive: false, sort_order: 201 },
  { title: "Dúo Dinámico", description: "Juega 10 partidos ganando con el mismo compañero", category: "SOCIAL", condition_type: "SAME_PARTNER_WINS", condition_value: 10, reward_type: "STAT_BOOST", reward_value: { league_overall: 0.5 }, is_pro_exclusive: false, sort_order: 202 },
  { title: "Hermanos de Cancha", description: "Juega 20 partidos ganando con el mismo compañero", category: "SOCIAL", condition_type: "SAME_PARTNER_WINS", condition_value: 20, reward_type: "COSMETIC", reward_value: { cosmetic_key: "duo_frame", cosmetic_type: "FRAME" }, is_pro_exclusive: true, sort_order: 203 },
  { title: "Capitán", description: "Organiza 10 partidos", category: "SOCIAL", condition_type: "MATCHES_ORGANIZED", condition_value: 10, reward_type: "STAT_BOOST", reward_value: { league_overall: 0.5 }, is_pro_exclusive: false, sort_order: 211 },
  { title: "Director de Cancha", description: "Organiza 25 partidos", category: "SOCIAL", condition_type: "MATCHES_ORGANIZED", condition_value: 25, reward_type: "STAT_BOOST", reward_value: { technique: 1 }, is_pro_exclusive: false, sort_order: 212 },
  { title: "Anfitrión de Leyenda", description: "Organiza 50 partidos", category: "SOCIAL", condition_type: "MATCHES_ORGANIZED", condition_value: 50, reward_type: "COSMETIC", reward_value: { cosmetic_key: "captain_frame", cosmetic_type: "FRAME" }, is_pro_exclusive: true, sort_order: 213 },
  { title: "Fiel", description: "Juega al menos 1 partido por semana durante 4 semanas seguidas", category: "SOCIAL", condition_type: "WEEKS_ACTIVE_STREAK", condition_value: 4, reward_type: "STAT_BOOST", reward_value: { pace: 1 }, is_pro_exclusive: false, sort_order: 221 },
  { title: "Comprometido", description: "Juega al menos 1 partido por semana durante 8 semanas", category: "SOCIAL", condition_type: "WEEKS_ACTIVE_STREAK", condition_value: 8, reward_type: "STAT_BOOST", reward_value: { league_overall: 0.5, physical: 0.5 }, is_pro_exclusive: false, sort_order: 222 },
  { title: "Imparable", description: "Juega al menos 1 partido por semana durante 12 semanas", category: "SOCIAL", condition_type: "WEEKS_ACTIVE_STREAK", condition_value: 12, reward_type: "COSMETIC", reward_value: { cosmetic_key: "loyalty_banner", cosmetic_type: "BANNER" }, is_pro_exclusive: true, sort_order: 223 },
  { title: "Votante Activo", description: "Emite 20 votos en partidos", category: "SOCIAL", condition_type: "VOTES_CAST", condition_value: 20, reward_type: "STAT_BOOST", reward_value: { technique: 0.5 }, is_pro_exclusive: false, sort_order: 231 },
  { title: "Crítico Justo", description: "Emite 50 votos en partidos", category: "SOCIAL", condition_type: "VOTES_CAST", condition_value: 50, reward_type: "STAT_BOOST", reward_value: { league_overall: 0.25 }, is_pro_exclusive: false, sort_order: 232 },
  { title: "Subiendo", description: "Alcanza el Top 10 del ranking de tu liga", category: "RANKING", condition_type: "LEAGUE_RANK_REACHED", condition_value: 10, reward_type: "STAT_BOOST", reward_value: { pace: 0.5 }, is_pro_exclusive: false, sort_order: 301 },
  { title: "Top 5", description: "Alcanza el Top 5 del ranking de tu liga", category: "RANKING", condition_type: "LEAGUE_RANK_REACHED", condition_value: 5, reward_type: "STAT_BOOST", reward_value: { league_overall: 0.5 }, is_pro_exclusive: false, sort_order: 302 },
  { title: "Podio", description: "Alcanza el Top 3 del ranking de tu liga", category: "RANKING", condition_type: "LEAGUE_RANK_REACHED", condition_value: 3, reward_type: "STAT_BOOST", reward_value: { technique: 1, attack: 0.5 }, is_pro_exclusive: false, sort_order: 303 },
  { title: "Campeón", description: "Lidera el ranking de tu liga", category: "RANKING", condition_type: "LEAGUE_RANK_REACHED", condition_value: 1, reward_type: "COSMETIC", reward_value: { cosmetic_key: "champion_frame", cosmetic_type: "FRAME" }, is_pro_exclusive: true, sort_order: 304 },
  { title: "Rating Constante", description: "Mantén un promedio de 7.0 en 5 partidos seguidos", category: "RANKING", condition_type: "AVG_RATING_OVER_MATCHES", condition_value: 7, reward_type: "STAT_BOOST", reward_value: { league_overall: 0.5 }, is_pro_exclusive: false, sort_order: 311 },
  { title: "Rating Estrella", description: "Mantén un promedio de 8.0 en 5 partidos seguidos", category: "RANKING", condition_type: "AVG_RATING_OVER_MATCHES", condition_value: 8, reward_type: "STAT_BOOST", reward_value: { technique: 1 }, is_pro_exclusive: false, sort_order: 312 },
  { title: "Rating Legendario", description: "Mantén un promedio de 8.5 en 10 partidos seguidos", category: "RANKING", condition_type: "AVG_RATING_OVER_MATCHES", condition_value: 8.5, reward_type: "COSMETIC", reward_value: { cosmetic_key: "accent_frame", cosmetic_type: "FRAME" }, is_pro_exclusive: true, sort_order: 313 },
  { title: "Fénix", description: "Gana un MVP justo después de haber sido Tronco en el partido anterior", category: "MATCH", condition_type: "TRONCO_THEN_MVP", condition_value: 1, reward_type: "STAT_BOOST", reward_value: { physical: 1 }, is_pro_exclusive: false, sort_order: 401 },
  { title: "Resurrección", description: "Fénix: de Tronco a MVP. Desbloquea marco especial.", category: "MATCH", condition_type: "TRONCO_THEN_MVP", condition_value: 1, reward_type: "COSMETIC", reward_value: { cosmetic_key: "phoenix_frame", cosmetic_type: "FRAME" }, is_pro_exclusive: true, sort_order: 402 },
  { title: "Mala Racha", description: "Pierde 3 partidos seguidos", category: "STREAK", condition_type: "LOSS_STREAK", condition_value: 3, reward_type: "COSMETIC", reward_value: { cosmetic_key: "ghost_frame", cosmetic_type: "FRAME" }, is_pro_exclusive: true, sort_order: 411 },
  { title: "Cuesta Arriba", description: "Pierde 5 partidos seguidos (pero no te rindas)", category: "STREAK", condition_type: "LOSS_STREAK", condition_value: 5, reward_type: "COSMETIC", reward_value: { cosmetic_key: "ghost_frame", cosmetic_type: "FRAME" }, is_pro_exclusive: true, sort_order: 412 },
  { title: "Tronco Honesto", description: "Recibe 3 votos de Tronco (con orgullo)", category: "MATCH", condition_type: "TRONCO_COUNT", condition_value: 3, reward_type: "STAT_BOOST", reward_value: { physical: 0.5 }, is_pro_exclusive: false, sort_order: 421 },
  { title: "Tronco Profesional", description: "Recibe 5 votos de Tronco", category: "MATCH", condition_type: "TRONCO_COUNT", condition_value: 5, reward_type: "COSMETIC", reward_value: { cosmetic_key: "trunk_badge", cosmetic_type: "BADGE" }, is_pro_exclusive: true, sort_order: 422 },
  { title: "Fantasma", description: "No te presentes a un partido al que fuiste convocado", category: "MATCH", condition_type: "FANTASMA_COUNT", condition_value: 1, reward_type: "STAT_BOOST", reward_value: { pace: 0.25 }, is_pro_exclusive: false, sort_order: 431 },
  { title: "Fantasma Recurrente", description: "Acumula 3 Fantasmas (el equipo te recuerda)", category: "MATCH", condition_type: "FANTASMA_COUNT", condition_value: 3, reward_type: "COSMETIC", reward_value: { cosmetic_key: "danger_frame", cosmetic_type: "FRAME" }, is_pro_exclusive: true, sort_order: 432 },
  { title: "Duelista", description: "Gana tu primer duelo 1v1", category: "MATCH", condition_type: "DUEL_WINS", condition_value: 1, reward_type: "STAT_BOOST", reward_value: { attack: 0.5 }, is_pro_exclusive: false, sort_order: 501 },
  { title: "Duelista Consagrado", description: "Gana 5 duelos", category: "MATCH", condition_type: "DUEL_WINS", condition_value: 5, reward_type: "STAT_BOOST", reward_value: { technique: 1 }, is_pro_exclusive: false, sort_order: 502 },
  { title: "Rey del Duelo", description: "Gana 10 duelos", category: "MATCH", condition_type: "DUEL_WINS", condition_value: 10, reward_type: "COSMETIC", reward_value: { cosmetic_key: "duel_frame", cosmetic_type: "FRAME" }, is_pro_exclusive: true, sort_order: 503 },
  { title: "Gladiador", description: "Gana 25 duelos", category: "MATCH", condition_type: "DUEL_WINS", condition_value: 25, reward_type: "COSMETIC", reward_value: { cosmetic_key: "gladiator_banner", cosmetic_type: "BANNER" }, is_pro_exclusive: true, sort_order: 504 },
  { title: "Adivino", description: "Acierta 5 predicciones correctas", category: "MATCH", condition_type: "PREDICTION_CORRECT", condition_value: 5, reward_type: "STAT_BOOST", reward_value: { technique: 0.5 }, is_pro_exclusive: false, sort_order: 601 },
  { title: "Oráculo", description: "Acierta 15 predicciones correctas", category: "MATCH", condition_type: "PREDICTION_CORRECT", condition_value: 15, reward_type: "STAT_BOOST", reward_value: { league_overall: 0.5 }, is_pro_exclusive: false, sort_order: 602 },
  { title: "Bola de Cristal", description: "Acierta 30 predicciones correctas", category: "MATCH", condition_type: "PREDICTION_CORRECT", condition_value: 30, reward_type: "COSMETIC", reward_value: { cosmetic_key: "oracle_frame", cosmetic_type: "FRAME" }, is_pro_exclusive: true, sort_order: 603 },
  { title: "Vidente", description: "Acierta 50 predicciones correctas", category: "MATCH", condition_type: "PREDICTION_CORRECT", condition_value: 50, reward_type: "COSMETIC", reward_value: { cosmetic_key: "crystal_ball_banner", cosmetic_type: "BANNER" }, is_pro_exclusive: true, sort_order: 604 },
  { title: "Coleccionista", description: "Desbloquea 5 logros de cualquier tipo", category: "RANKING", condition_type: "ACHIEVEMENTS_UNLOCKED", condition_value: 5, reward_type: "COSMETIC", reward_value: { cosmetic_key: "accent_emerald", cosmetic_type: "BADGE" }, is_pro_exclusive: true, sort_order: 701 },
  { title: "Maestro", description: "Desbloquea 15 logros", category: "RANKING", condition_type: "ACHIEVEMENTS_UNLOCKED", condition_value: 15, reward_type: "COSMETIC", reward_value: { cosmetic_key: "neon_frame", cosmetic_type: "FRAME" }, is_pro_exclusive: true, sort_order: 702 },
  { title: "Leyenda", description: "Desbloquea 25 logros", category: "RANKING", condition_type: "ACHIEVEMENTS_UNLOCKED", condition_value: 25, reward_type: "COSMETIC", reward_value: { cosmetic_key: "neon_banner", cosmetic_type: "BANNER" }, is_pro_exclusive: true, sort_order: 703 },
  { title: "Ícono", description: "Desbloquea 40 logros", category: "RANKING", condition_type: "ACHIEVEMENTS_UNLOCKED", condition_value: 40, reward_type: "COSMETIC", reward_value: { cosmetic_key: "accent_crimson", cosmetic_type: "BADGE" }, is_pro_exclusive: true, sort_order: 704 },
  { title: "Exhibicionista", description: "Completa 10 misiones con recompensa cosmética", category: "RANKING", condition_type: "COSMETIC_ACHIEVEMENTS_CLAIMED", condition_value: 10, reward_type: "COSMETIC", reward_value: { cosmetic_key: "trophy_showcase", cosmetic_type: "BADGE" }, is_pro_exclusive: true, sort_order: 711 },
  { title: "Vitrina de Oro", description: "Completa 20 misiones con recompensa cosmética", category: "RANKING", condition_type: "COSMETIC_ACHIEVEMENTS_CLAIMED", condition_value: 20, reward_type: "COSMETIC", reward_value: { cosmetic_key: "gold_showcase", cosmetic_type: "BADGE" }, is_pro_exclusive: true, sort_order: 712 },
  { title: "Primera Victoria", description: "Gana tu primer partido", category: "MATCH", condition_type: "MATCHES_WON", condition_value: 1, reward_type: "STAT_BOOST", reward_value: { attack: 0.5 }, is_pro_exclusive: false, sort_order: 801 },
  { title: "Diez Victorias", description: "Gana 10 partidos", category: "MATCH", condition_type: "MATCHES_WON", condition_value: 10, reward_type: "STAT_BOOST", reward_value: { pace: 0.5 }, is_pro_exclusive: false, sort_order: 802 },
  { title: "Cincuenta Victorias", description: "Gana 50 partidos", category: "MATCH", condition_type: "MATCHES_WON", condition_value: 50, reward_type: "STAT_BOOST", reward_value: { league_overall: 0.5, defense: 0.5 }, is_pro_exclusive: false, sort_order: 803 },
  { title: "Centenario", description: "Gana 100 partidos", category: "MATCH", condition_type: "MATCHES_WON", condition_value: 100, reward_type: "COSMETIC", reward_value: { cosmetic_key: "century_banner", cosmetic_type: "BANNER" }, is_pro_exclusive: true, sort_order: 804 },
  { title: "Todo Terreno", description: "Saca 8 o más en 3 stats diferentes en un mismo partido", category: "MATCH", condition_type: "MULTI_STAT_8_SINGLE", condition_value: 3, reward_type: "STAT_BOOST", reward_value: { league_overall: 0.5 }, is_pro_exclusive: false, sort_order: 811 },
  { title: "Pentacampeón", description: "Saca 8 o más en los 5 stats en un mismo partido", category: "MATCH", condition_type: "MULTI_STAT_8_SINGLE", condition_value: 5, reward_type: "COSMETIC", reward_value: { cosmetic_key: "all_rounder_frame", cosmetic_type: "FRAME" }, is_pro_exclusive: true, sort_order: 812 },
  { title: "Remontada", description: "Gana un partido después de ir perdiendo a mitad de tiempo", category: "MATCH", condition_type: "COMEBACK_WIN", condition_value: 1, reward_type: "STAT_BOOST", reward_value: { physical: 1 }, is_pro_exclusive: false, sort_order: 821 },
  { title: "Rey de la Remontada", description: "Gana 5 partidos remontando", category: "MATCH", condition_type: "COMEBACK_WIN", condition_value: 5, reward_type: "COSMETIC", reward_value: { cosmetic_key: "comeback_frame", cosmetic_type: "FRAME" }, is_pro_exclusive: true, sort_order: 822 },
  { title: "Confirmado", description: "Confirma asistencia a 10 partidos", category: "SOCIAL", condition_type: "MATCHES_CONFIRMED", condition_value: 10, reward_type: "STAT_BOOST", reward_value: { technique: 0.5 }, is_pro_exclusive: false, sort_order: 831 },
  { title: "Siempre Listo", description: "Confirma asistencia a 25 partidos", category: "SOCIAL", condition_type: "MATCHES_CONFIRMED", condition_value: 25, reward_type: "STAT_BOOST", reward_value: { pace: 0.5 }, is_pro_exclusive: false, sort_order: 832 },
  { title: "Superador", description: "Supera a un rival en el ranking que iba por encima de ti", category: "RANKING", condition_type: "RANK_OVERTAKE", condition_value: 1, reward_type: "STAT_BOOST", reward_value: { attack: 0.5 }, is_pro_exclusive: false, sort_order: 841 },
  { title: "Cazador de Puestos", description: "Supera a 5 rivales en el ranking en una temporada", category: "RANKING", condition_type: "RANK_OVERTAKE", condition_value: 5, reward_type: "COSMETIC", reward_value: { cosmetic_key: "accent_neon_blue", cosmetic_type: "BADGE" }, is_pro_exclusive: true, sort_order: 842 },
  { title: "Sin Faltar", description: "Juega 5 partidos seguidos sin ser Fantasma", category: "STREAK", condition_type: "MATCHES_NO_FANTASMA_STREAK", condition_value: 5, reward_type: "STAT_BOOST", reward_value: { physical: 0.5 }, is_pro_exclusive: false, sort_order: 851 },
  { title: "Fiabilidad Total", description: "Juega 15 partidos seguidos sin ser Fantasma", category: "STREAK", condition_type: "MATCHES_NO_FANTASMA_STREAK", condition_value: 15, reward_type: "STAT_BOOST", reward_value: { league_overall: 0.5 }, is_pro_exclusive: false, sort_order: 852 },
  // --- Vitrina PRO: desbloqueo de items para mostrar (SHOWCASE) ---
  { title: "Estrella Emergente", description: "Gana tu primer MVP. Recompensa: poder mostrar tus MVPs en la vitrina.", category: "MATCH", condition_type: "MVP_COUNT", condition_value: 1, reward_type: "COSMETIC", reward_value: { cosmetic_key: "showcase_mvp", cosmetic_type: "SHOWCASE" }, is_pro_exclusive: true, sort_order: 901 },
  { title: "Promedio Constante", description: "Mantén un promedio de 7.0 o más en tus últimos 5 partidos. Recompensa: mostrar Promedio Histórico en la vitrina.", category: "RANKING", condition_type: "AVG_RATING_OVER_MATCHES", condition_value: 7, reward_type: "COSMETIC", reward_value: { cosmetic_key: "showcase_avg_hist", cosmetic_type: "SHOWCASE" }, is_pro_exclusive: true, sort_order: 902 },
  { title: "Gran Partido", description: "Saca 8 o más de nota general en un partido. Recompensa: poder mostrar tu Mejor Nota en la vitrina.", category: "MATCH", condition_type: "OVERALL_SINGLE", condition_value: 8, reward_type: "COSMETIC", reward_value: { cosmetic_key: "showcase_best_rating", cosmetic_type: "SHOWCASE" }, is_pro_exclusive: true, sort_order: 903 },
  { title: "Tres en la Cancha", description: "Juega 3 partidos confirmados. Recompensa: poder mostrar tu Último Partido en la vitrina.", category: "MATCH", condition_type: "MATCHES_PLAYED", condition_value: 3, reward_type: "COSMETIC", reward_value: { cosmetic_key: "showcase_last_match", cosmetic_type: "SHOWCASE" }, is_pro_exclusive: true, sort_order: 904 },
  { title: "Tronco con Orgullo", description: "Recibe 3 votos de Tronco en partidos. Recompensa: poder mostrar tus Troncos en la vitrina.", category: "MATCH", condition_type: "TRONCO_COUNT", condition_value: 3, reward_type: "COSMETIC", reward_value: { cosmetic_key: "showcase_tronco", cosmetic_type: "SHOWCASE" }, is_pro_exclusive: true, sort_order: 905 },
  { title: "Primer Duelo", description: "Gana tu primer duelo 1v1. Recompensa: poder mostrar Duelos ganados en la vitrina.", category: "MATCH", condition_type: "DUEL_WINS", condition_value: 1, reward_type: "COSMETIC", reward_value: { cosmetic_key: "showcase_duel", cosmetic_type: "SHOWCASE" }, is_pro_exclusive: true, sort_order: 906 },
  { title: "Adivino en Vitrina", description: "Acierta 5 predicciones correctas en el Prode. Recompensa: poder mostrar Oracles en la vitrina.", category: "MATCH", condition_type: "PREDICTION_CORRECT", condition_value: 5, reward_type: "COSMETIC", reward_value: { cosmetic_key: "showcase_oracle", cosmetic_type: "SHOWCASE" }, is_pro_exclusive: true, sort_order: 907 },
];

async function main() {
  const count = await prisma.achievements.count();
  if (count > 0) {
    console.log(`Ya existen ${count} logros. Saltando seed. (Para reinsertar, vacía la tabla achievements antes)`);
    return;
  }
  await prisma.achievements.createMany({ data: achievementsData });
  console.log(`✅ Insertados ${achievementsData.length} logros correctamente.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
